version: '3.8'
services:
  nginx:
    build: nginx
    labels:
      - traefik.http.routers.nginx.rule=Host(`localhost`)


  reverse_proxy:
    image: traefik
    command:
    - --api.insecure=true # Enable Traefik dashboard
    - --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80" # Web sites
      - "8080:8080" # Traefik dashboard