version: '3.8'
services:

  reverse_proxy:
    image: traefik
    command:
    - --api.insecure=true # Enable Traefik dashboard
    - --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80" # Web sites
      - "8080:8080" # Traefik dashboard

  javaserver:
    image: dai-lab-https-java-server-1
    expose:
      - 80
    build:
      context: .
    labels:
      - traefik.http.routers.javaserver.rule=Host(`localhost`) && PathPrefix(`/api`)
      - traefik.http.services.javaserver.loadbalancer.sticky=true
      - traefik.http.services.javaserver.loadbalancer.sticky.cookie.name=StickyCookie
#      - traefik.http.services.javaserver.loadbalancer.sticky.cookie.secure=true
    deploy:
      replicas: 2

  nginx:
    build: nginx
    labels:
      - traefik.http.routers.nginx.rule=Host(`localhost`)
    deploy:
      replicas: 2