version: '3.8'
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile  # Spécifie le nom du Dockerfile
    ports:
      - "8080:80"  # Associe le port 8080 de l'hôte au port 80 du conteneur
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Montage du fichier de configuration
      - ./nginx/html:/usr/share/nginx/html  # Montage du dossier contenant les fichiers statiques